#+TITLE: Sources

** Books
- [[https://www.packtpub.com/big-data-and-business-intelligence/building-machine-learning-systems-python-second-edition][Building Machine Learning Systems with Python]], Willi Richert, Luis
  Pedro Coelho, ISBN 978-1-78216-140-0
- [[http://shop.oreilly.com/product/0636920030515.do][Introduction to Machine Learning with Python - A Guide for Data
  Scientists]], Andreas C. Müller, Sarah Guido, O'Reilly Media, 2016,
  ISBN-13: 978-1449369415
- [[https://www.packtpub.com/big-data-and-business-intelligence/learning-scikit-learn-machine-learning-python][Learning scikit-learn: Machine Learning in Python]], Raúl Garreta,
  Guillermo Moncecchi, ISBN 978-1783281930

** Publications in scientific journals

- Angermueller C, Pärnamaa T, Parts L, Stegle O. Deep learning for
  computational biology. Mol Syst Biol. 2016 Jul
  29;12(7):878. https://dx.doi.org/10.15252/msb.20156651 PMCID:
  PMC4965871.

- Libbrecht MW, Noble WS. Machine learning applications in genetics
  and genomics. Nat Rev Genet. 2015 Jun;16(6):321-32,
  https://dx.doi.org/10.1038/nrg3920,
  ([[https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5204302/][Free version on PubMedCentral]])

- Min S, Lee B, Yoon S. Deep learning in bioinformatics. Brief
  Bioinform. 2016 Jul 29. pii:
  bbw068. https://doi.org/10.1093/bib/bbw068 ([[https://arxiv.org/abs/1603.06430][Preprint on arXiv]])

- Yip KY, Cheng C, Gerstein M. Machine learning and genome annotation:
  a match meant to be? Genome Biol. 2013 May
  29;14(5):205. https://dx.doi.org/10.1186/gb-2013-14-5-205.

